name: Deploy Release

on:
  push:
    tags:
      - '*'

jobs:
  deploy_pypi:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: |
          pip install versioneer
          versioneer install
          python setup.py bdist_wheel
          python setup.py sdist
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}